---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: check workdir
        run: ls

      - name: Install node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install
        working-directory: webapp

      - name: Lint
        run: yarn lint
        working-directory: webapp

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image
        uses: docker/build-push-action@v4
        with:
          context: webapp
          file: webapp/Dockerfile
          push: true
          tags: audenaertcasper/webapp:latest